### ISSUE TITLE
Search/filter function in bookmark dropdowns

### ISSUE THREAD

**Issue by porkyfork** [igorlogius/bookmark-branch-porter#10]
**Is your feature request related to a problem? Please describe.**
Yes see this issue:
https://github.com/igorlogius/bookmark-branch-porter/issues/9#issuecomment-1959179782

**Describe the solution you'd like**

It would be good to have a search facility in your Addon, so maybe instead of a drop down, the full list is displayed in a dialogue - like as with your debuggin out put window (but more legible), but you can then search it to help locate folders that are not always where you think they should be be, The Bookmarks side bar (and BSP2) order the list so the Bookmarks Toolbar is above the Bookmarks Menu, and that is where I expected to find it, not under the Bookmarks Menu.

![306956082-6e896c72-48a4-4081-a881-cb4eb85d98bc](https://github.com/igorlogius/bookmark-branch-porter/assets/157956613/5d3474bc-a51f-4b70-b65e-38f23c92c8b7)

**Describe alternatives you've considered**

**Additional context**

**Comment by igorlogius** [comment]
This should be the solution:

- https://www.hongkiat.com/blog/search-select-using-datalist/
- https://devdoc.net/web/developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist.html

But for whatever reason ... the option page doesnt show the dropdown ... needs some more investigation

**Comment by igorlogius** [comment]
ok, since datalist dont seem to work i opted for a rather drastic but ... also rather effectiv alternative. 

With version `1.4.14` everything is now done via the context menu of a bookmark folder. 
Meaning, you right click on the bookmark folder you want to import into or export and done. 

And since bookmarks can already be searched/filtered, this issue should be resolved.
Not the way i initally planned this ... since new users might have a bit of trouble figuring out how to use the addon, but ... i hope it's not too much of an issue. ... Time will tell.
