### ISSUE TITLE
 "Bookmarks Toolbar" entry missing in dropdowns

### ISSUE THREAD

**Issue by porkyfork** [igorlogius/bookmark-branch-porter#9]
**Is your feature request related to a problem? Please describe.**
I cant see the Bookmarks Toolbar Folder in the 'Export Drop down', this is the folder I wish to export.

**Describe the solution you'd like**
Add Bookmarks Toolbar Folder to the Export drop down

**Describe alternatives you've considered**
Will try look through the code, although I am not a programmer

**Additional context**

**Comment by igorlogius** [comment]
I briefly checked and as far as i can see the "Bookmark Toolbar" Folder it is part of the list

![Screenshot_2024-02-16_09-49-47](https://github.com/igorlogius/bookmark-branch-porter/assets/67047467/17bf2466-3d2d-4d78-be5d-4df5ecf9b4a9)

You can try creating a second browser profile and see if the issue persists.

**Comment by porkyfork** [comment]
Thanks for the swift reply.
I created a new profile, and could then see Bookmarks Toolbar in the list of folders to export.

I am using these bookmark addons:

Bookmark Search Plus 2
Autosort Bookmarks

I tried turning them off to see if that made a difference, but still couldn't see 'Bookmarks Toolbar' in the export list.

**Comment by igorlogius** [comment]
Interesting. I've never seen this before. 

My usual assumption since it seems to only be profile related would be that something about config setting is interfering, but i never heard of an setting that would do something like this, so i am at a bit of a lose.

I installed the 2 addons without making any preference changes you mention and that did not seem to influence the drop down, as far as i could see. 

Since the Drop Down Entry is completely missing for you ... i assume the `getBookmarkTree` function doesnt return it as an element, which is very strange.

**Comment by igorlogius** [comment]
Is the "Bookmarks Toolbar" visible in the import dropdown?

**Comment by porkyfork** [comment]
No, cannot see it there either ....

**Comment by igorlogius** [comment]
> No, cannot see it there either ....

ok, that is kind of good news, because the big is consistent and we can assume its not some kind of display or rendering issue.

Lets check what the getTree function really returns on your system.

1. download this zip file [bookmark_branch_porter-1.3.12.1.zip](https://github.com/igorlogius/bookmark-branch-porter/files/14324383/bookmark_branch_porter-1.3.12.1.zip)
2. enter `about:debugging` in a new tab in the address bar and hit enter
3. On the left side, click on "This Firefox"
4. Under the section "Temporary Extensions" click on the "Load Temporary Add-on.." Button and select the zip file from step 1. The Result should look something like this: 

![Screenshot_2024-02-18_21-38-07](https://github.com/igorlogius/bookmark-branch-porter/assets/67047467/6cb70668-116a-4f30-b9b6-8e35c99d4b1a)

5. Now  Click the "Inspect" Button, this should open a new window, where you have to switch to the "Console" view/tab
6. Keep that Window with the Console tab open 
7. Switch back to the main Firefox Window and now click the Toolbar Button of the addon 
8. In the console window there should have been some output generated.
9. Please check if the there is a `"title": "Bookmarks Toolbar"` line or share the result with and i'll take a look.

**Comment by porkyfork** [comment]
It generated just this short bit of code:
![image](https://github.com/igorlogius/bookmark-branch-porter/assets/157956613/176352a6-a235-4e77-bc85-c4dfae7a182f)

**Comment by igorlogius** [comment]
You should be able to scroll down further ... but you might have to click on the triangle/arrow at the top/beginning to expand the whole output first

**Comment by porkyfork** [comment]
Thanks, yes triangle opened up all the code, but FF was very sluggish (not responding) and crashed twice, popped "title": "Bookmarks Toolbar" into the filter - but nothing was filtered, but then put "title":"Bookmarks into filter, but it still found nothing.
Is there a way to export the 'consoles output to search in something else , like VS ?

**Comment by igorlogius** [comment]
Try right clicking on the unexpaned element/text. There should be an option to copy it into the clipboard from where you should be able to paste it into any editor, like notepad++ or similar

**Comment by igorlogius** [comment]
Sidenote: Maybe we already found the reason for the reaon for the issue. The 16.000 bookmarks might be too much ... but it is kind of strange that only one Folder would get truncated ... 

Seeing the full output might give a bit more insight here.

**Comment by porkyfork** [comment]
OK, I had an issue with a Folder with 1000's of bookmarks duplicate itself:
https://github.com/aaFn/Bookmark-search-plus-2/issues/292
I've since resolved that, and binned the deleted/duped bookmarks, so the number of bookmarks in FF is now down to approx 6000.
However even with that number the console is incredibly sliggish, and difficult to work with, when you expand the list and click on it to right click and copy ... it collapses the list and copies just the first 3 entries as screen grabbed above ... is there another way to get the output into a file - that I can then opne in Notepad++ or VS.
Thanks

**Comment by igorlogius** [comment]
I'll provide you with another debug build, wish should allow you to grab the entire output. 
Come back to you later, with the link to the zip file.

**Comment by igorlogius** [comment]
Here the zip file

[bookmark_branch_porter-1.3.12.2.zip](https://github.com/igorlogius/bookmark-branch-porter/files/14359396/bookmark_branch_porter-1.3.12.2.zip)

After installation as before, there should now be a textarea on the preference page, where you should be able to copy the output from. Should look something like this: 

![Screenshot_2024-02-21_13-29-00](https://github.com/igorlogius/bookmark-branch-porter/assets/67047467/66894497-fb76-4aac-8a7a-ec6be5673f77)

**Comment by porkyfork** [comment]
Its found ... took a while using Notepad++ and VS to see where in the huge long list it was, it was actually almost at the bottom of the list ... so now I can locate it in your extensions drop down ... Solved :) Thanks for your help.

It would be good to have a search facility in your Addon, maybe instead of a drop down, the full list is displayed in a dialogue, but you can then search it to help locate folders that are not always where you think they should be be, The Bookmarks side bar (and BSP2) order the list so the Bookmarks Toolbar is above the Bookmarks Menu, and that is where I expected to find it.

![image](https://github.com/igorlogius/bookmark-branch-porter/assets/157956613/6e896c72-48a4-4081-a881-cb4eb85d98bc)

**Comment by igorlogius** [comment]
Ok, then lets do this one step at a time. 
First we close this issue. (done) 

Then i would request you to open a "Search in Dropdown" Feature Request issue and i'll see what i can do.

**Comment by porkyfork** [comment]
Hi I have just gone to use the addon to export just the Bookmarks Toolbar to hmtl, however when I open it the content in Firefox or Notepad++ it is illegible, almost as if it is raw encrypted data.
The json file opens in Notepad++ and looks fine.
 ... any idea please.

**Comment by igorlogius** [comment]
> Hi I have just gone to use the addon to export just the Bookmarks Toolbar to hmtl, however when I open the exported html content in Firefox or Notepad++ it is illegible, almost as if it is raw encrypted data. The json file opens in Notepad++ and looks fine. ... any idea please.

Not sure but maybe some kind of encoding issue. Maybe some bookmarks use some strange charachter in their titles? Hard to tell from a distance.

**Comment by porkyfork** [comment]
I have tested the extension by exporting various folders, ie Bookmarks Menu, Bookmarks Toolbar, and a subfolder of - as html, and then opening in Firefox.

All open as if they are appear encryted, the screen is filled with what appear like random characters.

![image](https://github.com/igorlogius/bookmark-branch-porter/assets/157956613/66b13474-ada5-472f-b9b8-8000c8b8791e)

I have then use the Export as HMTL in the Bookmarks manager, and the file opens fine in Firefox.

The Bookmarks manager HMTL export is approx 15mb, where as the Extension's file size is 1340k.

**Comment by igorlogius** [comment]
This might help.
